version: '3.2'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - home:/home/hocus/
      - .:/home/hocus/.hocus-mount/
    command: sleep infinity

volumes:
  home:
