version: '3.2'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - home:/home/hocus/

      - .:/home/hocus/.hocus-mount/
      - ./user/vscode-settings.json:/home/hocus/.vscode-server/data/Machine/settings.json
    command: sleep infinity

volumes:
  home:
